table d_meta_mensal
	lineageTag: 7c59a7bd-85bf-4e1d-b994-3924971c566d

	column meta_novas_apolices
		dataType: double
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 9fbc30f6-0455-4f62-84f1-27b8129aa01a
		summarizeBy: sum
		sourceColumn: meta_novas_apolices

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column meta_receita_premios
		dataType: double
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 69a98b6e-e1f6-4fa0-9109-104f8eed6951
		summarizeBy: sum
		sourceColumn: meta_receita_premios

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column meta_taxa_churn
		dataType: double
		lineageTag: b88d4bef-b59c-4825-b351-52c36d50f9ae
		summarizeBy: sum
		sourceColumn: meta_taxa_churn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: f096c50d-41fc-4feb-a0c7-0b3ee81e73ff
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: 6047d806-4b85-4faa-b386-7902a47beb7e
			defaultHierarchy: LocalDateTable_8d7763e2-d3b0-46d0-a2b0-1eed07519803.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition d_meta_mensal = m
		mode: import
		queryGroup: dimensoes
		source =
				let
				    Fonte = Database{[Name = "vw_meta_mensal"]}[Data],
				    Tipar = Table.TransformColumnTypes(Fonte,{{"data", type date}})
				in
				    Tipar

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

